### ISSUE TITLE
TMacWebBrowserService visibility

### ISSUE THREAD

**Issue by s-buchner** [freeonterminate/delphi#1]
Hi,
In my code I needed to get access to the NSView like this:

TMacWebBrowserService(FWebBrowser).getView()

To make this possible I had to alter your source code and make TMacWebBrowserService declared in the interface and make getView public.

Is it possible you make the type accessible like in the above code? 
I would like to stick to your version of the code.

thanks for your work
Sascha

**Comment by freeonterminate** [comment]
GetView moved to Protected. 
You can use GetView, FWebBrowser cast to TOpenMacWebBrowserService.
TOpenMacWebBrowserService is following code.
TOpenMacWebBrowserService = class(TMacWebBrowserService);
