### ISSUE TITLE
Returning the result of EvaluateJavaScript in WebbrowserEx

### ISSUE THREAD

**Issue by andre2007** [freeonterminate/delphi#3]
It would be really nice if you can change the procedure EvaluateJavaScript to a function with return type String. I want to execute Javascript coding and get the result as String.

For example: 
document.getElementById("aaa").value
document.getElementById("bbb").checked

Operation System Windows 10 with Delphi 10.2 Tokyo

**Comment by freeonterminate** [comment]
Please use "ScriptGate"
https://bitbucket.org/freeonterminate/scriptgate

**Comment by andre2007** [comment]
Thanks a lot!
