### ISSUE TITLE
keydown event in Javascript

### ISSUE THREAD

**Issue by otkeri** [freeonterminate/delphi#5]
I want to grap that ESC Key in Javascript keydown event. But the operation is not work in FMX.TWebBrowserEx.

O/S : Windows

The Javascript example code is http://samples.msdn.microsoft.com/workshop/samples/author/dhtml/refs/onkeydown.htm

Also I tried to grap the ESC key in TWebBrowser.TranslateAccelerator  function, But the function is not work.

**Comment by freeonterminate** [comment]
Please try "ScriptGate" and FMX.TWebBrowser .
https://bitbucket.org/freeonterminate/scriptgate

**Comment by otkeri** [comment]
Thank you so much for your answer.

I See. but I want to detect the Special function Keys on TWebbrowser.  
Examples are  F1, F2, ... ESC.
All Special funtion Key events is not  happend. 
The event is not happend on Delphi TWebbrowser Component.
There is no howto.
Please!

**Comment by otkeri** [comment]
Thank you very much for your answer.

but Also I cannot detect then Special function keys in ScriptGate demo.
Examples are F1, F2, ... f10, ESC keys.
There is no howto anywhere.
:(

**Comment by otkeri** [comment]
It does work well. it's my mistake.
